name: tc_transfer_env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=12.4.127=0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-libraries-dev=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvrtc-dev=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.6=3
  - debugpy=1.8.11=py310h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - faiss=1.8.0=py310cuda120h9349f21_1_cuda
  - faiss-gpu=1.8.0=h3722977_2
  - filelock=3.13.1=py310haa95532_0
  - gmpy2=2.1.2=py310h7f96b67_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py310haa95532_0
  - ipython=8.30.0=py310haa95532_0
  - ipywidgets=8.1.5=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.4=py310haa95532_1
  - jupyter_client=8.6.0=py310haa95532_0
  - jupyter_core=5.7.2=py310haa95532_0
  - jupyterlab_widgets=3.0.13=py310haa95532_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libcblas=3.9.0=8_h719fc58_netlib
  - libcublas=12.4.5.8=0
  - libcublas-dev=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufft-dev=11.2.1.3=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.6.1.9=0
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libcusparse-dev=12.3.1.170=0
  - libfaiss=1.8.0=cuda120h2ee710b_1_cuda
  - libffi=3.4.4=hd77b12b_1
  - liblapack=3.9.0=8_h719fc58_netlib
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libsodium=1.0.18=h62dcd97_0
  - libuv=1.48.0=h827c3e9_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.3=py310h827c3e9_1
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py310haa95532_0
  - msys2-conda-epoch=20160418=1
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.3=py310haa95532_0
  - numpy=1.26.4=py310hf667824_0
  - openssl=3.4.0=ha4e3fda_1
  - packaging=24.2=py310haa95532_0
  - parso=0.8.4=py310haa95532_0
  - pip=24.2=py310haa95532_0
  - platformdirs=3.10.0=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py310h827c3e9_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py310haa95532_1
  - python=3.10.16=h4607a30_1
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda12.4_cudnn9_0
  - pytorch-cuda=12.4=h3fd98bf_7
  - pytorch-mutex=1.0=cuda
  - pywin32=308=py310h5da7b33_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=26.2.0=py310h5da7b33_0
  - setuptools=75.1.0=py310haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py310h827c3e9_0
  - traitlets=5.14.3=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.44.0=py310haa95532_0
  - widgetsnbextension=4.0.13=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - alembic==1.14.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - blosc2==2.7.1
      - certifi==2024.12.14
      - cesnet-datazoo==0.1.10
      - cesnet-models==0.4.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - colorlog==6.9.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.55.3
      - fsspec==2024.12.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - hydra-core==1.3.2
      - idna==3.10
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - kmedoids==0.5.3.1
      - mako==1.3.9
      - matplotlib==3.10.0
      - msgpack==1.1.0
      - ndindex==1.9.2
      - numexpr==2.10.2
      - omegaconf==2.3.0
      - optuna==4.2.1
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==6.31.1
      - py-cpuinfo==9.0.0
      - pyarrow==12.0.0
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyparsing==3.2.1
      - pytz==2024.2
      - requests==2.32.3
      - rich==13.9.4
      - rich-click==1.8.5
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - sentry-sdk==2.30.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sqlalchemy==2.0.38
      - sympy==1.13.1
      - tables==3.9.2
      - tcbench==0.0.22
      - threadpoolctl==3.5.0
      - torchinfo==1.8.0
      - tqdm==4.67.1
      - tzdata==2024.2
      - urllib3==2.3.0
      - wandb==0.20.1
